name: blaze
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  blaze_engine:
    path: ../blaze_engine
  shared_preferences: ^2.0.11
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  path_provider: ^2.1.5
  system_tray: ^2.0.3
  desktop_window: ^0.4.2
  window_manager: ^0.4.3
  dbus: ^0.7.10
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/